import {mutation, query} from '@convex/_generated/server'
import {paginationOptsValidator} from 'convex/server'
import {v} from 'convex/values'

const nullableNumber = v.union(v.number(), v.null())
const nullableString = v.union(v.string(), v.null())
const chatKind = v.union(v.literal('bot'), v.literal('group'), v.literal('supergroup'))
const eventKind = v.union(v.literal('command'), v.literal('message'), v.literal('flow'), v.literal('entry'), v.literal('error'), v.literal('system'))
const eventStatus = v.union(v.literal('ok'), v.literal('ignored'), v.literal('rejected'), v.literal('error'))
const messageKind = v.union(v.literal('text'), v.literal('link'), v.literal('photo'), v.literal('voice'), v.literal('audio'), v.literal('document'), v.literal('video'), v.literal('sticker'), v.literal('unsupported'))

const eventContext = v.object({
  updateId: nullableNumber,
  messageId: nullableNumber,
  textLength: nullableNumber,
  errorName: nullableString,
  reason: nullableString,
})

const emptyContext = {
  updateId: null,
  messageId: null,
  textLength: null,
  errorName: null,
  reason: null,
}

export const record = mutation({
  args: {
    userId: v.optional(v.union(v.id('users'), v.null())),
    telegramId: v.optional(nullableNumber),
    chatId: v.optional(nullableNumber),
    chatKind: v.optional(v.union(chatKind, v.null())),
    kind: eventKind,
    action: v.string(),
    status: eventStatus,
    command: v.optional(nullableString),
    messageKind: v.optional(v.union(messageKind, v.null())),
    entryId: v.optional(v.union(v.id('entries'), v.null())),
    flowId: v.optional(v.union(v.id('flows'), v.null())),
    context: v.optional(eventContext),
  },
  returns: v.object({
    eventId: v.id('botEvents'),
  }),
  handler: async (ctx, args) => {
    const eventId = await ctx.db.insert('botEvents', {
      userId: args.userId ?? null,
      telegramId: args.telegramId ?? null,
      chatId: args.chatId ?? null,
      chatKind: args.chatKind ?? null,
      source: 'telegram',
      kind: args.kind,
      action: args.action,
      status: args.status,
      command: args.command ?? null,
      messageKind: args.messageKind ?? null,
      entryId: args.entryId ?? null,
      flowId: args.flowId ?? null,
      context: args.context ?? emptyContext,
      createdAt: Date.now(),
    })

    return {eventId}
  },
})

export const listByUser = query({
  args: {
    userId: v.id('users'),
    limit: v.optional(v.number()),
  },
  returns: v.array(
    v.object({
      _id: v.id('botEvents'),
      _creationTime: v.number(),
      userId: v.union(v.id('users'), v.null()),
      telegramId: nullableNumber,
      chatId: nullableNumber,
      chatKind: v.union(chatKind, v.null()),
      source: v.literal('telegram'),
      kind: eventKind,
      action: v.string(),
      status: eventStatus,
      command: nullableString,
      messageKind: v.union(messageKind, v.null()),
      entryId: v.union(v.id('entries'), v.null()),
      flowId: v.union(v.id('flows'), v.null()),
      context: eventContext,
      createdAt: v.number(),
    }),
  ),
  handler: async (ctx, args) => {
    const limit = Math.min(Math.max(args.limit ?? 50, 1), 100)
    return await ctx.db
      .query('botEvents')
      .withIndex('by_userId_and_createdAt', (q) => q.eq('userId', args.userId))
      .order('desc')
      .take(limit)
  },
})

export const listByTelegram = query({
  args: {
    telegramId: v.number(),
    limit: v.optional(v.number()),
  },
  returns: v.array(
    v.object({
      _id: v.id('botEvents'),
      _creationTime: v.number(),
      userId: v.union(v.id('users'), v.null()),
      telegramId: nullableNumber,
      chatId: nullableNumber,
      chatKind: v.union(chatKind, v.null()),
      source: v.literal('telegram'),
      kind: eventKind,
      action: v.string(),
      status: eventStatus,
      command: nullableString,
      messageKind: v.union(messageKind, v.null()),
      entryId: v.union(v.id('entries'), v.null()),
      flowId: v.union(v.id('flows'), v.null()),
      context: eventContext,
      createdAt: v.number(),
    }),
  ),
  handler: async (ctx, args) => {
    const limit = Math.min(Math.max(args.limit ?? 50, 1), 100)
    return await ctx.db
      .query('botEvents')
      .withIndex('by_telegramId_and_createdAt', (q) => q.eq('telegramId', args.telegramId))
      .order('desc')
      .take(limit)
  },
})

// ! DO NOT UPDATE MANNUALLY THIS PART – it's generated by the script `scripts/gen-db-meta.mjs`
// db-gen:base:start
export const length = query({
  args: {},
  returns: v.object({
    count: v.number(),
    isTruncated: v.boolean(),
  }),
  handler: async (ctx) => {
    const rows = await ctx.db.query('botEvents').take(5000)
    return {count: rows.length, isTruncated: rows.length === 5000}
  },
})

export const list = query({
  args: {paginationOpts: paginationOptsValidator},
  returns: v.object({
    page: v.array(
      v.object({
        _id: v.id('botEvents'),
        _creationTime: v.number(),
        userId: v.union(v.id('users'), v.null()),
        telegramId: v.union(v.number(), v.null()),
        chatId: v.union(v.number(), v.null()),
        chatKind: v.union(v.literal('bot'), v.literal('group'), v.literal('supergroup'), v.null()),
        source: v.literal('telegram'),
        kind: v.union(v.literal('command'), v.literal('message'), v.literal('flow'), v.literal('entry'), v.literal('error'), v.literal('system')),
        action: v.string(),
        status: v.union(v.literal('ok'), v.literal('ignored'), v.literal('rejected'), v.literal('error')),
        command: v.union(v.string(), v.null()),
        messageKind: v.union(v.literal('text'), v.literal('link'), v.literal('photo'), v.literal('voice'), v.literal('audio'), v.literal('document'), v.literal('video'), v.literal('sticker'), v.literal('unsupported'), v.null()),
        entryId: v.union(v.id('entries'), v.null()),
        flowId: v.union(v.id('flows'), v.null()),
        context: v.object({
          updateId: v.union(v.number(), v.null()),
          messageId: v.union(v.number(), v.null()),
          textLength: v.union(v.number(), v.null()),
          errorName: v.union(v.string(), v.null()),
          reason: v.union(v.string(), v.null()),
        }),
        createdAt: v.number(),
      }),
    ),
    isDone: v.boolean(),
    continueCursor: v.string(),
  }),
  handler: async (ctx, args) => {
    return await ctx.db.query('botEvents').order('desc').paginate(args.paginationOpts)
  },
})

export const getById = query({
  args: {id: v.id('botEvents')},
  returns: v.union(
    v.object({
      _id: v.id('botEvents'),
      _creationTime: v.number(),
      userId: v.union(v.id('users'), v.null()),
      telegramId: v.union(v.number(), v.null()),
      chatId: v.union(v.number(), v.null()),
      chatKind: v.union(v.literal('bot'), v.literal('group'), v.literal('supergroup'), v.null()),
      source: v.literal('telegram'),
      kind: v.union(v.literal('command'), v.literal('message'), v.literal('flow'), v.literal('entry'), v.literal('error'), v.literal('system')),
      action: v.string(),
      status: v.union(v.literal('ok'), v.literal('ignored'), v.literal('rejected'), v.literal('error')),
      command: v.union(v.string(), v.null()),
      messageKind: v.union(v.literal('text'), v.literal('link'), v.literal('photo'), v.literal('voice'), v.literal('audio'), v.literal('document'), v.literal('video'), v.literal('sticker'), v.literal('unsupported'), v.null()),
      entryId: v.union(v.id('entries'), v.null()),
      flowId: v.union(v.id('flows'), v.null()),
      context: v.object({
        updateId: v.union(v.number(), v.null()),
        messageId: v.union(v.number(), v.null()),
        textLength: v.union(v.number(), v.null()),
        errorName: v.union(v.string(), v.null()),
        reason: v.union(v.string(), v.null()),
      }),
      createdAt: v.number(),
    }),
    v.null(),
  ),
  handler: async (ctx, args) => {
    return await ctx.db.get('botEvents', args.id)
  },
})

export const create = mutation({
  args: {
    doc: v.object({
      userId: v.union(v.id('users'), v.null()),
      telegramId: v.union(v.number(), v.null()),
      chatId: v.union(v.number(), v.null()),
      chatKind: v.union(v.literal('bot'), v.literal('group'), v.literal('supergroup'), v.null()),
      source: v.literal('telegram'),
      kind: v.union(v.literal('command'), v.literal('message'), v.literal('flow'), v.literal('entry'), v.literal('error'), v.literal('system')),
      action: v.string(),
      status: v.union(v.literal('ok'), v.literal('ignored'), v.literal('rejected'), v.literal('error')),
      command: v.union(v.string(), v.null()),
      messageKind: v.union(v.literal('text'), v.literal('link'), v.literal('photo'), v.literal('voice'), v.literal('audio'), v.literal('document'), v.literal('video'), v.literal('sticker'), v.literal('unsupported'), v.null()),
      entryId: v.union(v.id('entries'), v.null()),
      flowId: v.union(v.id('flows'), v.null()),
      context: v.object({
        updateId: v.union(v.number(), v.null()),
        messageId: v.union(v.number(), v.null()),
        textLength: v.union(v.number(), v.null()),
        errorName: v.union(v.string(), v.null()),
        reason: v.union(v.string(), v.null()),
      }),
      createdAt: v.number(),
    }),
  },
  returns: v.id('botEvents'),
  handler: async (ctx, args) => {
    return await ctx.db.insert('botEvents', args.doc)
  },
})

export const update = mutation({
  args: {
    id: v.id('botEvents'),
    patch: v.object({
      userId: v.optional(v.union(v.id('users'), v.null())),
      telegramId: v.optional(v.union(v.number(), v.null())),
      chatId: v.optional(v.union(v.number(), v.null())),
      chatKind: v.optional(v.union(v.literal('bot'), v.literal('group'), v.literal('supergroup'), v.null())),
      source: v.optional(v.literal('telegram')),
      kind: v.optional(v.union(v.literal('command'), v.literal('message'), v.literal('flow'), v.literal('entry'), v.literal('error'), v.literal('system'))),
      action: v.optional(v.string()),
      status: v.optional(v.union(v.literal('ok'), v.literal('ignored'), v.literal('rejected'), v.literal('error'))),
      command: v.optional(v.union(v.string(), v.null())),
      messageKind: v.optional(v.union(v.literal('text'), v.literal('link'), v.literal('photo'), v.literal('voice'), v.literal('audio'), v.literal('document'), v.literal('video'), v.literal('sticker'), v.literal('unsupported'), v.null())),
      entryId: v.optional(v.union(v.id('entries'), v.null())),
      flowId: v.optional(v.union(v.id('flows'), v.null())),
      context: v.optional(
        v.object({
          updateId: v.union(v.number(), v.null()),
          messageId: v.union(v.number(), v.null()),
          textLength: v.union(v.number(), v.null()),
          errorName: v.union(v.string(), v.null()),
          reason: v.union(v.string(), v.null()),
        }),
      ),
      createdAt: v.optional(v.number()),
    }),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.patch('botEvents', args.id, args.patch)
    return null
  },
})

export const remove = mutation({
  args: {id: v.id('botEvents')},
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id)
    return null
  },
})
// db-gen:base:end
