import {mutation, query} from '@convex/_generated/server'
import {paginationOptsValidator} from 'convex/server'
import {v} from 'convex/values'

// ! DO NOT UPDATE MANNUALLY THIS PART – it's generated by the script `scripts/gen-db-meta.mjs`
// db-gen:base:start
export const length = query({
  args: {},
  returns: v.object({
    count: v.number(),
    isTruncated: v.boolean(),
  }),
  handler: async (ctx) => {
    const rows = await ctx.db.query('entryTags').take(5000)
    return {count: rows.length, isTruncated: rows.length === 5000}
  },
})

export const list = query({
  args: {paginationOpts: paginationOptsValidator},
  returns: v.object({
    page: v.array(
      v.object({
        _id: v.id('entryTags'),
        _creationTime: v.number(),
        userId: v.id('users'),
        entryId: v.id('entries'),
        tagId: v.id('tags'),
        createdAt: v.number(),
      }),
    ),
    isDone: v.boolean(),
    continueCursor: v.string(),
  }),
  handler: async (ctx, args) => {
    return await ctx.db.query('entryTags').order('desc').paginate(args.paginationOpts)
  },
})

export const getById = query({
  args: {id: v.id('entryTags')},
  returns: v.union(
    v.object({
      _id: v.id('entryTags'),
      _creationTime: v.number(),
      userId: v.id('users'),
      entryId: v.id('entries'),
      tagId: v.id('tags'),
      createdAt: v.number(),
    }),
    v.null(),
  ),
  handler: async (ctx, args) => {
    return await ctx.db.get('entryTags', args.id)
  },
})

export const create = mutation({
  args: {
    doc: v.object({
      userId: v.id('users'),
      entryId: v.id('entries'),
      tagId: v.id('tags'),
      createdAt: v.number(),
    }),
  },
  returns: v.id('entryTags'),
  handler: async (ctx, args) => {
    return await ctx.db.insert('entryTags', args.doc)
  },
})

export const update = mutation({
  args: {
    id: v.id('entryTags'),
    patch: v.object({
      userId: v.optional(v.id('users')),
      entryId: v.optional(v.id('entries')),
      tagId: v.optional(v.id('tags')),
      createdAt: v.optional(v.number()),
    }),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.patch('entryTags', args.id, args.patch)
    return null
  },
})

export const remove = mutation({
  args: {id: v.id('entryTags')},
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id)
    return null
  },
})
// db-gen:base:end
