import {mutation, query} from '@convex/_generated/server'
import {paginationOptsValidator} from 'convex/server'
import {v} from 'convex/values'

export const upsertActive = mutation({
  args: {
    userId: v.id('users'),
    chatId: v.number(),
    kind: v.literal('tag'),
    entryId: v.id('entries'),
  },
  returns: v.object({
    status: v.union(v.literal('created'), v.literal('replaced')),
    flowId: v.id('flows'),
  }),
  handler: async (ctx, args) => {
    const now = Date.now()
    const existing = await ctx.db
      .query('flows')
      .withIndex('by_userId_and_chatId_and_status', (q) => q.eq('userId', args.userId).eq('chatId', args.chatId).eq('status', 'active'))
      .unique()

    if (existing !== null) {
      await ctx.db.patch(existing._id, {
        kind: args.kind,
        entryId: args.entryId,
        step: 'tag',
        updatedAt: now,
      })

      return {
        status: 'replaced' as const,
        flowId: existing._id,
      }
    }

    const flowId = await ctx.db.insert('flows', {
      userId: args.userId,
      chatId: args.chatId,
      kind: args.kind,
      status: 'active',
      entryId: args.entryId,
      step: 'tag',
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
    })

    return {
      status: 'created' as const,
      flowId,
    }
  },
})

// ! DO NOT UPDATE MANNUALLY THIS PART – it's generated by the script `scripts/gen-db-meta.mjs`
// db-gen:base:start
export const length = query({
  args: {},
  returns: v.object({
    count: v.number(),
    isTruncated: v.boolean(),
  }),
  handler: async (ctx) => {
    const rows = await ctx.db.query('flows').take(5000)
    return {count: rows.length, isTruncated: rows.length === 5000}
  },
})

export const list = query({
  args: {paginationOpts: paginationOptsValidator},
  returns: v.object({
    page: v.array(
      v.object({
        _id: v.id('flows'),
        _creationTime: v.number(),
        userId: v.id('users'),
        chatId: v.number(),
        kind: v.literal('tag'),
        status: v.union(v.literal('active'), v.literal('done'), v.literal('cancelled')),
        entryId: v.union(v.id('entries'), v.null()),
        step: v.string(),
        createdAt: v.number(),
        updatedAt: v.number(),
        expiresAt: v.union(v.number(), v.null()),
      }),
    ),
    isDone: v.boolean(),
    continueCursor: v.string(),
  }),
  handler: async (ctx, args) => {
    return await ctx.db.query('flows').order('desc').paginate(args.paginationOpts)
  },
})

export const getById = query({
  args: {id: v.id('flows')},
  returns: v.union(
    v.object({
      _id: v.id('flows'),
      _creationTime: v.number(),
      userId: v.id('users'),
      chatId: v.number(),
      kind: v.literal('tag'),
      status: v.union(v.literal('active'), v.literal('done'), v.literal('cancelled')),
      entryId: v.union(v.id('entries'), v.null()),
      step: v.string(),
      createdAt: v.number(),
      updatedAt: v.number(),
      expiresAt: v.union(v.number(), v.null()),
    }),
    v.null(),
  ),
  handler: async (ctx, args) => {
    return await ctx.db.get('flows', args.id)
  },
})

export const create = mutation({
  args: {
    doc: v.object({
      userId: v.id('users'),
      chatId: v.number(),
      kind: v.literal('tag'),
      status: v.union(v.literal('active'), v.literal('done'), v.literal('cancelled')),
      entryId: v.union(v.id('entries'), v.null()),
      step: v.string(),
      createdAt: v.number(),
      updatedAt: v.number(),
      expiresAt: v.union(v.number(), v.null()),
    }),
  },
  returns: v.id('flows'),
  handler: async (ctx, args) => {
    return await ctx.db.insert('flows', args.doc)
  },
})

export const update = mutation({
  args: {
    id: v.id('flows'),
    patch: v.object({
      userId: v.optional(v.id('users')),
      chatId: v.optional(v.number()),
      kind: v.optional(v.literal('tag')),
      status: v.optional(v.union(v.literal('active'), v.literal('done'), v.literal('cancelled'))),
      entryId: v.optional(v.union(v.id('entries'), v.null())),
      step: v.optional(v.string()),
      createdAt: v.optional(v.number()),
      updatedAt: v.optional(v.number()),
      expiresAt: v.optional(v.union(v.number(), v.null())),
    }),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.patch('flows', args.id, args.patch)
    return null
  },
})

export const remove = mutation({
  args: {id: v.id('flows')},
  returns: v.null(),
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id)
    return null
  },
})
// db-gen:base:end
