import {mutation, query} from '@convex/_generated/server'
import {paginationOptsValidator} from 'convex/server'
import {v} from 'convex/values'

const TELEGRAM_USERNAME_RE = /^[a-z0-9_]{3,30}$/

function normalizeUsername(raw: string): string {
  return raw.trim().replace(/^@+/, '').toLowerCase()
}

export const submit = mutation({
  args: {
    username: v.string(),
  },
  returns: v.union(v.object({status: v.literal('created'), id: v.id('waitlist')}), v.object({status: v.literal('duplicate')}), v.object({status: v.literal('invalid'), message: v.string()})),
  handler: async (ctx, args) => {
    const username = normalizeUsername(args.username)
    if (!TELEGRAM_USERNAME_RE.test(username)) {
      return {
        status: 'invalid' as const,
        message: 'Никнейм: 3–30 символа, латиница, цифры и подчёркивание.',
      }
    }

    const existing = await ctx.db
      .query('waitlist')
      .withIndex('by_username', (q) => q.eq('username', username))
      .unique()

    if (existing !== null) {
      return {status: 'duplicate' as const}
    }

    const telegramLink = `https://t.me/${username}`
    const id = await ctx.db.insert('waitlist', {
      username,
      telegramLink,
    })

    return {status: 'created' as const, id}
  },
})

// ! DO NOT UPDATE MANNUALLY THIS PART – it's generated by the script `scripts/gen-db-meta.mjs`
// db-gen:base:start
export const length = query({
  args: {},
  handler: async (ctx) => {
    const rows = await ctx.db.query('waitlist').take(5000)
    return {count: rows.length, isTruncated: rows.length === 5000}
  },
})

export const list = query({
  args: {paginationOpts: paginationOptsValidator},
  handler: async (ctx, args) => {
    return await ctx.db.query('waitlist').order('desc').paginate(args.paginationOpts)
  },
})

export const getById = query({
  args: {id: v.id('waitlist')},
  handler: async (ctx, args) => {
    return await ctx.db.get('waitlist', args.id)
  },
})

export const create = mutation({
  args: {
    doc: v.object({
      username: v.string(),
      telegramLink: v.string(),
    }),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert('waitlist', args.doc)
  },
})

export const update = mutation({
  args: {
    id: v.id('waitlist'),
    patch: v.object({
      username: v.optional(v.string()),
      telegramLink: v.optional(v.string()),
    }),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch('waitlist', args.id, args.patch)
    return null
  },
})

export const remove = mutation({
  args: {id: v.id('waitlist')},
  handler: async (ctx, args) => {
    await ctx.db.delete(args.id)
    return null
  },
})
// db-gen:base:end
