// This file is auto-generated by scripts/gen-db-meta.mjs. Do not edit manually.

export type FieldMeta =
  | {kind: 'string' | 'number' | 'boolean' | 'int64' | 'bytes' | 'null'; optional: boolean}
  | {kind: 'id'; table: string; optional: boolean}
  | {kind: 'enum'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean}
  | {kind: 'literal'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean}
  | {kind: 'array'; of: FieldMeta; optional: boolean}
  | {kind: 'object'; fields: Record<string, FieldMeta>; optional: boolean}
  | {kind: 'union'; options: FieldMeta[]; optional: boolean}
  | {kind: 'record'; optional: boolean}
  | {kind: 'unknown'; source: string; optional: boolean}

export const dbMeta = {
  "demo": {
    fields: {
      "username": {"kind":"string","optional":false},
    },
  },
  "waitlist": {
    fields: {
      "username": {"kind":"string","optional":false},
      "telegramLink": {"kind":"string","optional":false},
    },
  },
  "users": {
    fields: {
      "userId": {"kind":"number","optional":false},
      "username": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "firstName": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "lastName": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "languageCode": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "isPremium": {"kind":"union","options":[{"kind":"boolean","optional":false},{"kind":"null","optional":false}],"optional":false},
      "isBotAccount": {"kind":"boolean","optional":false},
      "botChatId": {"kind":"union","options":[{"kind":"number","optional":false},{"kind":"null","optional":false}],"optional":false},
      "lastChatId": {"kind":"number","optional":false},
      "lastChatKind": {"kind":"enum","valueType":"string","values":["bot","group","supergroup"],"optional":false},
      "firstSeenAt": {"kind":"number","optional":false},
      "lastSeenAt": {"kind":"number","optional":false},
      "lastStartAt": {"kind":"union","options":[{"kind":"number","optional":false},{"kind":"null","optional":false}],"optional":false},
      "startPayload": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "registrationSource": {"kind":"string","optional":false},
      "status": {"kind":"enum","valueType":"string","values":["new","active","blocked"],"optional":false},
      "isBlocked": {"kind":"boolean","optional":false},
      "blockedAt": {"kind":"union","options":[{"kind":"number","optional":false},{"kind":"null","optional":false}],"optional":false},
      "unblockedAt": {"kind":"union","options":[{"kind":"number","optional":false},{"kind":"null","optional":false}],"optional":false},
      "webAuthId": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "timezone": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "locale": {"kind":"union","options":[{"kind":"string","optional":false},{"kind":"null","optional":false}],"optional":false},
      "updatesCount": {"kind":"number","optional":false},
      "commandsCount": {"kind":"number","optional":false},
      "startsCount": {"kind":"number","optional":false},
      "mirroredCount": {"kind":"number","optional":false},
      "errorsCount": {"kind":"number","optional":false},
    },
  },
} as const

export type DbMeta = typeof dbMeta
export type DbTableName = keyof DbMeta & string
export type DbTableMeta<T extends DbTableName> = DbMeta[T]
