// This file is auto-generated by scripts/gen-db-meta.mjs. Do not edit manually.

export type FieldMeta = {kind: 'string' | 'number' | 'boolean' | 'int64' | 'bytes' | 'null'; optional: boolean} | {kind: 'id'; table: string; optional: boolean} | {kind: 'enum'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean} | {kind: 'literal'; valueType: 'string' | 'number' | 'boolean'; values: Array<string | number | boolean>; optional: boolean} | {kind: 'array'; of: FieldMeta; optional: boolean} | {kind: 'object'; fields: Record<string, FieldMeta>; optional: boolean} | {kind: 'union'; options: FieldMeta[]; optional: boolean} | {kind: 'record'; optional: boolean} | {kind: 'unknown'; source: string; optional: boolean}

export const dbMeta = {
  waitlist: {
    fields: {
      username: {kind: 'string', optional: false},
      telegramLink: {kind: 'string', optional: false},
      status: {kind: 'enum', valueType: 'string', values: ['active', 'converted', 'archived'], optional: true},
      createdAt: {kind: 'number', optional: true},
      updatedAt: {kind: 'number', optional: true},
    },
  },
  users: {
    fields: {
      telegramId: {kind: 'number', optional: false},
      username: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      botChatId: {
        kind: 'union',
        options: [
          {kind: 'number', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      webAuthId: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      status: {kind: 'enum', valueType: 'string', values: ['new', 'active', 'blocked'], optional: false},
      createdAt: {kind: 'number', optional: false},
      updatedAt: {kind: 'number', optional: false},
      lastSeenAt: {kind: 'number', optional: false},
      profile: {
        kind: 'object',
        fields: {
          firstName: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          lastName: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          languageCode: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          isPremium: {
            kind: 'union',
            options: [
              {kind: 'boolean', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          isBot: {kind: 'boolean', optional: false},
        },
        optional: false,
      },
      settings: {
        kind: 'object',
        fields: {
          timezone: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          locale: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
        },
        optional: false,
      },
      telegram: {
        kind: 'object',
        fields: {
          lastChatId: {kind: 'number', optional: false},
          lastChatKind: {kind: 'enum', valueType: 'string', values: ['bot', 'group', 'supergroup'], optional: false},
          lastStartAt: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          startPayload: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          registrationSource: {kind: 'string', optional: false},
        },
        optional: false,
      },
      stats: {kind: 'object', fields: {updates: {kind: 'number', optional: false}, commands: {kind: 'number', optional: false}, starts: {kind: 'number', optional: false}, captures: {kind: 'number', optional: false}, errors: {kind: 'number', optional: false}}, optional: false},
      moderation: {
        kind: 'object',
        fields: {
          blockedAt: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          unblockedAt: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
        },
        optional: false,
      },
    },
  },
  entries: {
    fields: {
      userId: {kind: 'id', table: 'users', optional: false},
      source: {kind: 'literal', valueType: 'string', values: ['telegram'], optional: false},
      sourceChatId: {kind: 'number', optional: false},
      sourceMessageId: {kind: 'number', optional: false},
      kind: {kind: 'enum', valueType: 'string', values: ['text', 'link', 'photo', 'voice', 'audio', 'document', 'video', 'sticker', 'unsupported'], optional: false},
      status: {kind: 'enum', valueType: 'string', values: ['inbox', 'saved', 'archived'], optional: false},
      text: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      description: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      descriptionSource: {kind: 'enum', valueType: 'string', values: ['none', 'text', 'caption', 'user', 'ai'], optional: false},
      url: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      telegram: {
        kind: 'object',
        fields: {
          type: {kind: 'string', optional: false},
          context: {
            kind: 'object',
            fields: {
              forwardOrigin: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              forwardDate: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              replyToMessageId: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
            },
            optional: false,
          },
          file: {
            kind: 'object',
            fields: {
              fileId: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              fileUniqueId: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              fileName: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              mimeType: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              fileSize: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              duration: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              width: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              height: {
                kind: 'union',
                options: [
                  {kind: 'number', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              emoji: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              setName: {
                kind: 'union',
                options: [
                  {kind: 'string', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              isAnimated: {
                kind: 'union',
                options: [
                  {kind: 'boolean', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
              isVideo: {
                kind: 'union',
                options: [
                  {kind: 'boolean', optional: false},
                  {kind: 'null', optional: false},
                ],
                optional: false,
              },
            },
            optional: false,
          },
        },
        optional: false,
      },
      createdAt: {kind: 'number', optional: false},
      updatedAt: {kind: 'number', optional: false},
      archivedAt: {
        kind: 'union',
        options: [
          {kind: 'number', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
    },
  },
  tags: {
    fields: {
      userId: {kind: 'id', table: 'users', optional: false},
      name: {kind: 'string', optional: false},
      slug: {kind: 'string', optional: false},
      createdAt: {kind: 'number', optional: false},
      updatedAt: {kind: 'number', optional: false},
    },
  },
  entryTags: {
    fields: {
      userId: {kind: 'id', table: 'users', optional: false},
      entryId: {kind: 'id', table: 'entries', optional: false},
      tagId: {kind: 'id', table: 'tags', optional: false},
      createdAt: {kind: 'number', optional: false},
    },
  },
  flows: {
    fields: {
      userId: {kind: 'id', table: 'users', optional: false},
      chatId: {kind: 'number', optional: false},
      kind: {kind: 'literal', valueType: 'string', values: ['tag'], optional: false},
      status: {kind: 'enum', valueType: 'string', values: ['active', 'done', 'cancelled'], optional: false},
      entryId: {
        kind: 'union',
        options: [
          {kind: 'id', table: 'entries', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      step: {kind: 'string', optional: false},
      createdAt: {kind: 'number', optional: false},
      updatedAt: {kind: 'number', optional: false},
      expiresAt: {
        kind: 'union',
        options: [
          {kind: 'number', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
    },
  },
  botEvents: {
    fields: {
      userId: {
        kind: 'union',
        options: [
          {kind: 'id', table: 'users', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      telegramId: {
        kind: 'union',
        options: [
          {kind: 'number', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      chatId: {
        kind: 'union',
        options: [
          {kind: 'number', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      chatKind: {
        kind: 'union',
        options: [
          {kind: 'literal', valueType: 'string', values: ['bot'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['group'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['supergroup'], optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      source: {kind: 'literal', valueType: 'string', values: ['telegram'], optional: false},
      kind: {kind: 'enum', valueType: 'string', values: ['command', 'message', 'flow', 'entry', 'error', 'system'], optional: false},
      action: {kind: 'string', optional: false},
      status: {kind: 'enum', valueType: 'string', values: ['ok', 'ignored', 'rejected', 'error'], optional: false},
      command: {
        kind: 'union',
        options: [
          {kind: 'string', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      messageKind: {
        kind: 'union',
        options: [
          {kind: 'literal', valueType: 'string', values: ['text'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['link'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['photo'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['voice'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['audio'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['document'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['video'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['sticker'], optional: false},
          {kind: 'literal', valueType: 'string', values: ['unsupported'], optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      entryId: {
        kind: 'union',
        options: [
          {kind: 'id', table: 'entries', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      flowId: {
        kind: 'union',
        options: [
          {kind: 'id', table: 'flows', optional: false},
          {kind: 'null', optional: false},
        ],
        optional: false,
      },
      context: {
        kind: 'object',
        fields: {
          updateId: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          messageId: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          textLength: {
            kind: 'union',
            options: [
              {kind: 'number', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          errorName: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
          reason: {
            kind: 'union',
            options: [
              {kind: 'string', optional: false},
              {kind: 'null', optional: false},
            ],
            optional: false,
          },
        },
        optional: false,
      },
      createdAt: {kind: 'number', optional: false},
    },
  },
} as const

export type DbMeta = typeof dbMeta
export type DbTableName = keyof DbMeta & string
export type DbTableMeta<T extends DbTableName> = DbMeta[T]
